import type { Metadata } from "next";
import { Lobster, Londrina_Solid, Mansalva } from "next/font/google";
import "./globals.css";

const mansalva = Mansalva({
  variable: "--font-mansalva",
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${mansalva.variable} antialiased`}>{children}</body>
    </html>
  );
}
